on:
  push:
    branches: [main]

jobs:
  publish-image:
    runs-on: codeberg-small
    permissions:
      packages: write
    steps:
    - name: Publish image
      uses: woodpecker-plugins/docker-buildx@latest
      with:
        platforms: linux/amd64
        repo: codeberg.org/${CI_REPO_OWNER}/dasBlog
        registry: codeberg.org
        tags: latest
        username: ${CI_REPO_OWNER}
        password: ${{secrets.DOCKER_TOKEN}}
